# Generated by Django 4.2.7 on 2023-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_filecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_content',
            field=models.ManyToManyField(to='notes.filecontent'),
        ),
    ]
